env:
  browser: true
  es2021: true
  jest: true

parser: "@typescript-eslint/parser"

settings:
  react:
    version: detect

globals:
  JSX: "readonly"

extends:
  - plugin:react/recommended
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended

overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: ["./tsconfig.json"]

plugins:
  - react
  - prettier
  - jest

rules:
  "prettier/prettier": ["error", endOfline: "auto"]
  "react/react-in-jsx-scope": "off"
