version: "3.8"
services:
  backend:
    image: "${CONTAINER_REGISTRY}/${BACKEND_IMAGE_NAME}:${BACKEND_IMAGE_TAG}"
    container_name: "${CONTAINER_PREFIX}_${BACKEND_CTAG}"
    depends_on:
      - postgres
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    networks:
      - net_softwareprojekt
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_USERNAME: "${BACKEND_DB_USER}"
      SPRING_DATASOURCE_PASSWORD: "${BACKEND_DB_PASSWORD}"
      SPRING_DATASOURCE_URL: "jdbc:${BACKEND_DB_DRIVER}://${BACKEND_DB_HOST}:${BACKEND_DB_PORT}/${BACKEND_DB_NAME}"
      SPRING_SERVER_HOST: "${BACKEND_HOST}"
      SPRING_SERVER_PORT: "${BACKEND_PORT}"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: "org.hibernate.dialect.${BACKEND_HIBERNATE_DIALECT}"

  postgres:
    image: "docker.io/postgres:${POSTGRES_IMAGE_TAG}"
    container_name: "${CONTAINER_PREFIX}_${POSTGRES_CTAG}"
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - type: volume
        source: v_postgres
        target: /data/postgres
        volume:
          nocopy: true
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - net_softwareprojekt
    restart: unless-stopped

  pgadmin:
    image: "dpage/pgadmin4:6.15"
    container_name: "${CONTAINER_PREFIX}_${PG_ADMIN_CTAG}"
    user: "0:0"
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - type: volume
        source: v_pgadmin
        target: /var/lib/pgadmin
        volume:
          nocopy: true
    ports:
      - "${PG_ADMIN_PORT}:80"
    networks:
      - net_softwareprojekt
    restart: unless-stopped

networks:
  net_softwareprojekt:
    driver: bridge
    name: "net_frontend_softwareprojekt"

volumes:
  v_postgres:
    driver: "local"
    name: "fhwedel_postgres"

  v_pgadmin:
    driver: "local"
    name: "fhwedel_pgadmin"
