# https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: 'jdbc:postgresql://${DB_HOST:dev-stundenplan-postgres}:5432/postgres'
    password: password
    username: postgres
  # flyway:
  #   enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  mvc:
    servlet:
      path: '/api'
  sql:
    init:
      mode: always
server:
  error:
    include-message: always
  servlet:
    session:
      cookie:
        same-site: strict
springdoc:
  swagger-ui:
    path: /docs
logging:
  level:
    com.fhwedel.softwareprojekt: 'info'
    org.springframework.web.filter.CommonsRequestLoggingFilter: 'debug'

custom:
  auth:
    access-token:
      secret: asdasdasdsadasdasdasdds
      duration: 1440

