version: "3.8"

services:
  frontend:
    image: "${CONTAINER_REGISTRY}/${FRONTEND_IMAGE_NAME}:${FRONTEND_IMAGE_TAG}"
    container_name: "${CONTAINER_PREFIX}_${FRONTEND_CTAG}"
    ports:
      - "${FRONTEND_PORT}:80"
    networks:
      - net_softwareprojekt
    restart: unless-stopped


  postgres:
    image: "docker.io/postgres:${POSTGRES_IMAGE_TAG}"
    container_name: "${CONTAINER_PREFIX}_${POSTGRES_CTAG}"
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - type: volume
        source: v_pgadmin
        target: /data/postgres
        volume:
          nocopy: true
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - net_softwareprojekt
    restart: unless-stopped

  pgadmin:
    image: "dpage/pgadmin4:6.15"
    container_name: "${CONTAINER_PREFIX}_${PG_ADMIN_CTAG}"
    user: "0:0"
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - type: volume
        source: v_pgadmin
        target: /var/lib/pgadmin
        volume:
          nocopy: true
    ports:
      - "${PG_ADMIN_PORT}:80"
    networks:
      - net_softwareprojekt
    restart: unless-stopped


networks:
  net_softwareprojekt:
    driver: bridge

volumes:
  v_postgres: 
    driver: "local"
    name: "dev_b_postgres"

  v_pgadmin: 
    driver: "local"
    name: "dev_b_pgadmin"
